apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hashicorp-vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: 0.30.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp-vault
  values:
    server:
      ha:
        enabled: false
        raft:
          enabled: true
      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: nfs-client-retain
        accessMode: ReadWriteMany
      ui:
        enabled: true