apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-pod-reader-binding
subjects:
- kind: ServiceAccount
  name: hashicorp-vault
roleRef:
  kind: Role
  name: vault-pod-reader
  apiGroup: rbac.authorization.k8s.io