apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:9vpZqTbYN44=,iv:aFNHNrL4ZvUmZeLzCddNJMWfQKQOGgfgFipbV+x9aI0=,tag:W+QlGipekjJ8fa/y6/3zBA==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:KcZ1t7HJB4Q=,iv:PKKeIhdOxnyxr4kjUA3ZLaYVmFgA7Ua43QcoZk3NI4E=,tag:0RqUhUyO7AseP1FLGqKi/w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: linkding-secrets
sops:
    age:
        - recipient: age1sq9h43p6w522rxjt8qckjp3w4n3jv86e54kj8cvwjtjdhdxk5v7qudz3uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQ1dDK29BOHV0eHRGWEVu
            ZHFpb3JJWW5HWUQ3Z3NEU01BYUVPYjlhMGdVCnY0S0phVzU2clVicUNXQjVlRGRX
            SlgxRTRHZXp4bU9mMGNnRTZMbXM2SmsKLS0tIFpBMmNua1hGU1o4eTBxTUhpcURx
            bUFZdWtXLy9NSzdPNjFzc1VjSzlsVEEKVFI8uHa2cEffbdjQ3Vtzh6vheFLsLabL
            i/dy0U+N4qAuULuXPaN+lUq+NwVSLk4REAm0BpuMW2/bKY4kbmbuiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T14:38:00Z"
    mac: ENC[AES256_GCM,data:cFVND+TS/SUCYLQmGwfWPPsvyaBtPc9aGJ2WORqgI5MZ1MY6aDIbztEF9wxbiNL8qtvgWkNzzvJ6MbpNU6sR7oLwNTQQviwUM226RB3XIoK7UQGLywvrShHj+KxbIA8+zREgfhZJboA+uoNi0BmfFGrlUwwMahJTHK2ejhIQ+gU=,iv:DN4iJ7eXTaPnDj/g4XxkZT9MgnC2T7O524OQTUoOdIM=,tag:E6ualhWOEkuFtlCuMXXwXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
