apiVersion: v1
data:
    password: ENC[AES256_GCM,data:yxCQOG8ee5I=,iv:qegki7ZSAf+b5K/xNTCCrdcLjmqZ0Un2ihblQm7+ouo=,tag:7+flpuXevrMmWY+N/ztHuA==,type:str]
    user: ENC[AES256_GCM,data:O2dlC80iJO4=,iv:Ji9D+Czp0mKx7uJlYXJDqp2gCEg6UuzjeevSQRTjukY=,tag:NSnGs4OSj2RE7Nl3lT1LKQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: test-secret
sops:
    age:
        - recipient: age1sq9h43p6w522rxjt8qckjp3w4n3jv86e54kj8cvwjtjdhdxk5v7qudz3uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeGpNamJDS3YvMXZMR1Z6
            dUlaMlc4b1Z3SFRPUEMrdkpLSFNGM2t6MkdvClBpTTc1ajNRbWNZeUNiaE8vNnY0
            ajBON3JsRlI3SWQrOUNYTkhWaTJjUU0KLS0tIDM2R1B0THQ1RFR4VFdNN09SZHVC
            UW10Ym92WnFFQ29zTFJqa3EwOHF4S3cKDPVw1b1HXttdlCdBSb/mJXIgTQYPGF+8
            EkoTF2LMnEc9OvyF5chN45Hf3moO4uO+Fwt/nhXZRrkYbewnqsjXSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-23T13:40:43Z"
    mac: ENC[AES256_GCM,data:KbGZYvWfn6F5AqkZTkAJi/zWqt04rD6BAQJ+2g64qGLF4sb1wo69aP1SgwiT5z7+xIGfrmB2y1WCAVmyrcp3rzXN2N/pXzKUJwBX+zj7Urwb5LtJduSFVKbdOEK1ce222uUFXIH1CdN2WofWMon/ilI8yvQPShFHIaeZsWf8w74=,iv:9Pa29ocTcKPMN/WCH6DUtFnJRGcF0xe20GTc9m/GxeI=,tag:VA0tRih5hIAbJih0/zCA/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
