apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: charts/v4.11.0/csi-driver-nfs
      sourceRef:
        kind: GitRepository
        name: csi-driver-nfs
        namespace: flux-system
  values:
    controller:
      replicas: 1
    node:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
    feature:
      enableFSGroupPolicy: false