apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.8.244
  share: /mnt/user/csi
reclaimPolicy: Delete
volumeBindingMode: Immediate