apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client-retain
  resources:
    requests:
      storage: 1Gi