apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:latest
              args:
                - albi986/homelab

              envFrom:
                - secretRef:
                    name: renovate-secret
                - configMapRef:
                    name: renovate-configmap

          restartPolicy: Never
